# Generated by Django 3.1.1 on 2020-09-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('', ''), ('CD', 'Cardiologist'), ('GE', 'Gastroenterologist'), ('GN', 'Gynecologist'), ('OB', 'Obstetrician'), ('PS', 'Psychiatrist')], default=' ', max_length=2)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=1, null=True)),
            ],
        ),
    ]
