# Generated by Django 3.1.1 on 2020-09-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_list',
            field=models.ManyToManyField(blank=True, to='doctors.Doctor'),
        ),
    ]
