# Generated by Django 3.1.1 on 2020-09-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_booked_appointments'),
        ('appointments', '0002_appointment_doctor_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_list',
            field=models.ManyToManyField(related_name='appointments', to='doctors.Doctor'),
        ),
    ]
